chore: develop -> main
NibiruChain/ts-sdk pull request #337
Opened 2024-03-11 19:56 UTC by CalicoNino

2024-03-11 19:58 UTC, cgilbe27 approved these changes

2024-03-11 21:23 UTC, CalicoNino commented
Needs: https://github.com/NibiruChain/go-heartmonitor/pull/270 to pass tests

2024-03-12 01:19 UTC, cgilbe27 requested changes
Requires hm PR

2024-03-12 13:39 UTC, cgilbe27 approved these changes

2024-03-12 13:39 UTC, merged